#! /usr/bin/env bash
# Facebook(facebook.com) Downfall of ssociety

if [ -f /etc/gpm.conf ]; then
    . /etc/gpm.conf
fi

. <(gpm-emit facebook)
GPM_name_field="email"
GPM_pass_field="pass"
cookieget https://www.facebook.com/login.php
"$GPM_user_bin_browser" "https://www.facebook.com/$@" &>/dev/null &
. <(gpm-c)
