#! /usr/bin/env bash

if [ -f /etc/gpm.conf ]; then
    . /etc/gpm.conf
fi

. <(gpm-emit twitter)
GPM_name_field="name"
GPM_pass_field="passwd"
cookieget https://www.twitter.com/login
"$GPM_user_bin_browser" "https://www.twitter.com/$@" &>/dev/null &
. <(gpm-c)
